import { resolvers } from '@/resolvers'
import { ApolloServer } from '@apollo/server'
import { ApolloFastifyContextFunction, fastifyApolloDrainPlugin, fastifyApolloHandler } from '@as-integrations/fastify'
import { UserType } from '@fastify/jwt'
import { PrismaClient } from '@prisma/client'
import { FastifyInstance, FastifyRequest, onRequestHookHandler } from 'fastify'
import path from 'path'
import { buildSchema } from 'type-graphql'
import { ResolversEnhanceMap, applyResolversEnhanceMap, resolvers as autoGeneratedResolvers } from '@typegraphql'
import { authChecker } from '../auth/authChecker'
import { EnvType } from '../env'

export interface Context {
  req: FastifyRequest
  user: UserType
  prisma: PrismaClient
  fastify: FastifyInstance
}

export interface createApolloServerOptions {
  prisma: PrismaClient
}

export async function createApolloServer(fastify: FastifyInstance, options: createApolloServerOptions) {
  const { prisma } = options

  const resolversEnhanceMap: ResolversEnhanceMap = {}

  applyResolversEnhanceMap(resolversEnhanceMap)

  const schema = await buildSchema({
    resolvers: [...autoGeneratedResolvers, ...resolvers],
    emitSchemaFile: path.resolve(__dirname, './generated-schema.graphql'),
    authChecker,
    validate: false,
  })

  const apollo = new ApolloServer<Context>({
    schema,
    plugins: [fastifyApolloDrainPlugin(fastify)],
  })

  const apolloContext: ApolloFastifyContextFunction<Context> = async (req, reply) => {
    return new Promise((resolve) => resolve({ req, user: req.user, prisma, fastify }))
  }

  const isEnv = fastify.getEnvs<EnvType>().NODE_ENV === 'development'
  const noAuthOnRequestHandler: onRequestHookHandler = (req, reply, done) => done()

  await apollo.start()

  fastify.route({
    method: ['POST', 'OPTIONS', 'GET'],
    url: '/graphql',
    onRequest: isEnv ? noAuthOnRequestHandler : fastify.auth([fastify.authenticate]),
    handler: fastifyApolloHandler(apollo, {
      context: apolloContext,
    }),
  })
}
